"""Add refresh_tokens table

Revision ID: 263c6aa8e011
Revises: a1b2c3d4e5f6
Create Date: 2025-11-16 13:02:41.295158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '263c6aa8e011'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='리프레시 토큰 고유 식별자'),
    sa.Column('userId', sa.UUID(), nullable=False, comment='사용자 ID'),
    sa.Column('token', sa.String(length=512), nullable=False, comment='리프레시 토큰 (해시값 저장)'),
    sa.Column('expiresAt', sa.DateTime(timezone=True), nullable=False, comment='토큰 만료 시각'),
    sa.Column('deviceInfo', sa.String(length=255), nullable=True, comment='디바이스 정보 (User-Agent 등)'),
    sa.Column('ipAddress', sa.String(length=45), nullable=True, comment='발급 시 IP 주소'),
    sa.Column('isRevoked', sa.Boolean(), server_default='false', nullable=False, comment='토큰 폐기 여부'),
    sa.Column('revokedAt', sa.DateTime(timezone=True), nullable=True, comment='폐기된 시각'),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 시각'),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('ix_refresh_tokens_expiresAt', 'refresh_tokens', ['expiresAt'], unique=False)
    op.create_index('ix_refresh_tokens_token', 'refresh_tokens', ['token'], unique=True)
    op.create_index('ix_refresh_tokens_userId', 'refresh_tokens', ['userId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_refresh_tokens_userId', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_token', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_expiresAt', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
