"""Initial migration: users, cards, user_card_activities, shares

Revision ID: 947b7042e023
Revises: 
Create Date: 2025-11-08 23:54:43.335023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '947b7042e023'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.UUID(), nullable=False, comment='카드 고유 식별자'),
    sa.Column('qr_code', sa.String(length=255), nullable=False, comment='QR 코드 값'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='카드 제목'),
    sa.Column('description', sa.Text(), nullable=True, comment='카드 설명'),
    sa.Column('activity_type', sa.String(length=100), nullable=False, comment='활동 유형 (season_select, drawing, quiz 등)'),
    sa.Column('activity_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='활동 옵션/설정 JSON'),
    sa.Column('thumbnail_url', sa.Text(), nullable=True, comment='카드 썸네일 이미지 URL'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='활성화 여부'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 시각'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_code')
    )
    op.create_index('ix_cards_activity_type', 'cards', ['activity_type'], unique=False)
    op.create_index('ix_cards_is_active', 'cards', ['is_active'], unique=False)
    op.create_index('ix_cards_qr_code', 'cards', ['qr_code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='사용자 고유 식별자'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='이메일 (로그인 ID)'),
    sa.Column('password', sa.String(length=255), nullable=True, comment='비밀번호 (bcrypt 해시, 소셜 로그인 시 NULL)'),
    sa.Column('username', sa.String(length=100), nullable=False, comment='사용자 이름'),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender_type'), nullable=True, comment='성별'),
    sa.Column('interest', sa.Enum('MEMORY_IMPROVEMENT', 'CONCENTRATION_TRAINING', 'LANGUAGE_ABILITY', 'MATH_ABILITY', name='interest_type'), nullable=True, comment='관심사'),
    sa.Column('phone_number', sa.String(length=20), nullable=True, comment='전화번호'),
    sa.Column('profile_image_url', sa.String(), nullable=True, comment='프로필 이미지 URL'),
    sa.Column('social_provider', sa.Enum('KAKAO', name='social_provider_type'), nullable=True, comment='소셜 로그인 제공자'),
    sa.Column('social_id', sa.String(length=255), nullable=True, comment='소셜 로그인 ID'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='계정 활성화 여부'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='마지막 로그인 시각'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 시각'),
    sa.CheckConstraint('\n            (password IS NOT NULL AND social_provider IS NULL AND social_id IS NULL) OR\n            (password IS NULL AND social_provider IS NOT NULL AND social_id IS NOT NULL)\n            ', name='chk_social_login'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_index('ix_users_social_login', 'users', ['social_provider', 'social_id'], unique=True, postgresql_where=sa.text('social_provider IS NOT NULL'))
    op.create_table('shares',
    sa.Column('id', sa.UUID(), nullable=False, comment='공유 링크 고유 식별자'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='공유 생성자'),
    sa.Column('card_id', sa.UUID(), nullable=False, comment='공유할 카드'),
    sa.Column('share_token', sa.String(length=255), nullable=False, comment='공유 토큰 (자동 생성)'),
    sa.Column('password', sa.String(length=255), nullable=True, comment='비밀번호 (bcrypt 해시, 선택)'),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True, comment='만료일 (선택)'),
    sa.Column('view_count', sa.Integer(), server_default='0', nullable=False, comment='조회수'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='활성화 여부'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 시각'),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token')
    )
    op.create_index('ix_shares_active_expiry', 'shares', ['is_active', 'expiry_date'], unique=False)
    op.create_index('ix_shares_card_id', 'shares', ['card_id'], unique=False)
    op.create_index('ix_shares_share_token', 'shares', ['share_token'], unique=True)
    op.create_index('ix_shares_user_active', 'shares', ['user_id', 'is_active'], unique=False)
    op.create_index('ix_shares_user_id', 'shares', ['user_id'], unique=False)
    op.create_table('user_card_activities',
    sa.Column('id', sa.UUID(), nullable=False, comment='활동 기록 고유 식별자'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='활동 수행 사용자'),
    sa.Column('card_id', sa.UUID(), nullable=False, comment='활동한 카드'),
    sa.Column('activity_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='사용자 활동 결과 JSON'),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='활동 완료 시각'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='기록 생성 시각'),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_card_activities_card_id', 'user_card_activities', ['card_id'], unique=False)
    op.create_index('ix_user_card_activities_completed_at', 'user_card_activities', ['completed_at'], unique=False)
    op.create_index('ix_user_card_activities_user_card', 'user_card_activities', ['user_id', 'card_id'], unique=False)
    op.create_index('ix_user_card_activities_user_completed', 'user_card_activities', ['user_id', 'completed_at'], unique=False)
    op.create_index('ix_user_card_activities_user_id', 'user_card_activities', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_card_activities_user_id', table_name='user_card_activities')
    op.drop_index('ix_user_card_activities_user_completed', table_name='user_card_activities')
    op.drop_index('ix_user_card_activities_user_card', table_name='user_card_activities')
    op.drop_index('ix_user_card_activities_completed_at', table_name='user_card_activities')
    op.drop_index('ix_user_card_activities_card_id', table_name='user_card_activities')
    op.drop_table('user_card_activities')
    op.drop_index('ix_shares_user_id', table_name='shares')
    op.drop_index('ix_shares_user_active', table_name='shares')
    op.drop_index('ix_shares_share_token', table_name='shares')
    op.drop_index('ix_shares_card_id', table_name='shares')
    op.drop_index('ix_shares_active_expiry', table_name='shares')
    op.drop_table('shares')
    op.drop_index('ix_users_social_login', table_name='users', postgresql_where=sa.text('social_provider IS NOT NULL'))
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_cards_qr_code', table_name='cards')
    op.drop_index('ix_cards_is_active', table_name='cards')
    op.drop_index('ix_cards_activity_type', table_name='cards')
    op.drop_table('cards')
    # ### end Alembic commands ###
