"""add notifications table

Revision ID: a1b2c3d4e5f6
Revises: beeffef1c2c8
Create Date: 2025-11-13 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = 'beeffef1c2c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='알림 고유 식별자'),
    sa.Column('userId', sa.UUID(), nullable=False, comment='수신자 사용자 ID'),
    sa.Column('type', sa.String(length=50), nullable=False, comment='알림 타입 (share_received, card_reminder 등)'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='알림 제목'),
    sa.Column('message', sa.String(), nullable=False, comment='알림 내용'),
    sa.Column('linkUrl', sa.String(), nullable=True, comment='링크 URL (선택)'),
    sa.Column('isRead', sa.Boolean(), server_default='false', nullable=False, comment='읽음 여부'),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 시각'),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_createdAt', 'notifications', ['createdAt'], unique=False)
    op.create_index('ix_notifications_userId', 'notifications', ['userId'], unique=False)
    op.create_index('ix_notifications_userId_isRead', 'notifications', ['userId', 'isRead'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_userId_isRead', table_name='notifications')
    op.drop_index('ix_notifications_userId', table_name='notifications')
    op.drop_index('ix_notifications_createdAt', table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
