"""add_server_default_uuid_generation

Revision ID: a2a34a32b972
Revises: 51b782cf1883
Create Date: 2025-11-09 01:27:10.193606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2a34a32b972'
down_revision: Union[str, None] = '51b782cf1883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add server_default for UUID columns
    op.alter_column('users', 'id',
                    server_default=sa.text('gen_random_uuid()'),
                    existing_type=sa.UUID(),
                    existing_nullable=False)

    op.alter_column('cards', 'id',
                    server_default=sa.text('gen_random_uuid()'),
                    existing_type=sa.UUID(),
                    existing_nullable=False)

    op.alter_column('user_card_activities', 'id',
                    server_default=sa.text('gen_random_uuid()'),
                    existing_type=sa.UUID(),
                    existing_nullable=False)

    op.alter_column('shares', 'id',
                    server_default=sa.text('gen_random_uuid()'),
                    existing_type=sa.UUID(),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove server_default for UUID columns
    op.alter_column('shares', 'id',
                    server_default=None,
                    existing_type=sa.UUID(),
                    existing_nullable=False)

    op.alter_column('user_card_activities', 'id',
                    server_default=None,
                    existing_type=sa.UUID(),
                    existing_nullable=False)

    op.alter_column('cards', 'id',
                    server_default=None,
                    existing_type=sa.UUID(),
                    existing_nullable=False)

    op.alter_column('users', 'id',
                    server_default=None,
                    existing_type=sa.UUID(),
                    existing_nullable=False)
    # ### end Alembic commands ###
