"""Initial migration with camelCase and userId

Revision ID: beeffef1c2c8
Revises: 
Create Date: 2025-11-10 20:09:51.968186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'beeffef1c2c8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='카드 고유 식별자'),
    sa.Column('qrCode', sa.String(length=255), nullable=False, comment='QR 코드 값'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='카드 제목'),
    sa.Column('description', sa.Text(), nullable=True, comment='카드 설명'),
    sa.Column('activityType', sa.String(length=100), nullable=False, comment='활동 유형 (season_select, drawing, quiz 등)'),
    sa.Column('activityData', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='활동 옵션/설정 JSON'),
    sa.Column('thumbnailUrl', sa.Text(), nullable=True, comment='카드 썸네일 이미지 URL'),
    sa.Column('isActive', sa.Boolean(), server_default='true', nullable=False, comment='활성화 여부'),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 시각'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qrCode')
    )
    op.create_index('ix_cards_activityType', 'cards', ['activityType'], unique=False)
    op.create_index('ix_cards_isActive', 'cards', ['isActive'], unique=False)
    op.create_index('ix_cards_qrCode', 'cards', ['qrCode'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='사용자 고유 식별자'),
    sa.Column('userId', sa.String(length=255), nullable=False, comment='로그인 id'),
    sa.Column('password', sa.String(length=255), nullable=True, comment='비밀번호 (bcrypt 해시, 소셜 로그인 시 NULL)'),
    sa.Column('userName', sa.String(length=100), nullable=False, comment='사용자 이름'),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender_type'), nullable=True, comment='성별'),
    sa.Column('interest', sa.Enum('MEMORY_IMPROVEMENT', 'CONCENTRATION_TRAINING', 'LANGUAGE_ABILITY', 'MATH_ABILITY', name='interest_type'), nullable=True, comment='관심사'),
    sa.Column('phoneNumber', sa.String(length=20), nullable=True, comment='전화번호'),
    sa.Column('profileImageUrl', sa.String(), nullable=True, comment='프로필 이미지 URL'),
    sa.Column('socialProvider', sa.Enum('KAKAO', name='social_provider_type'), nullable=True, comment='소셜 로그인 제공자'),
    sa.Column('socialId', sa.String(length=255), nullable=True, comment='소셜 로그인 ID'),
    sa.Column('isActive', sa.Boolean(), server_default='true', nullable=False, comment='계정 활성화 여부'),
    sa.Column('lastLoginAt', sa.DateTime(timezone=True), nullable=True, comment='마지막 로그인 시각'),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 시각'),
    sa.CheckConstraint('\n            (password IS NOT NULL AND "socialProvider" IS NULL AND "socialId" IS NULL) OR\n            (password IS NULL AND "socialProvider" IS NOT NULL AND "socialId" IS NOT NULL)\n            ', name='chk_social_login'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId')
    )
    op.create_index('ix_users_social_login', 'users', ['socialProvider', 'socialId'], unique=True, postgresql_where=sa.text('"socialProvider" IS NOT NULL'))
    op.create_index('ix_users_userId', 'users', ['userId'], unique=True)
    op.create_table('shares',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='공유 링크 고유 식별자'),
    sa.Column('userId', sa.UUID(), nullable=False, comment='공유 생성자'),
    sa.Column('cardId', sa.UUID(), nullable=False, comment='공유할 카드'),
    sa.Column('shareToken', sa.String(length=255), nullable=False, comment='공유 토큰 (자동 생성)'),
    sa.Column('password', sa.String(length=255), nullable=True, comment='비밀번호 (bcrypt 해시, 선택)'),
    sa.Column('expiryDate', sa.DateTime(timezone=True), nullable=True, comment='만료일 (선택)'),
    sa.Column('viewCount', sa.Integer(), server_default='0', nullable=False, comment='조회수'),
    sa.Column('isActive', sa.Boolean(), server_default='true', nullable=False, comment='활성화 여부'),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 시각'),
    sa.ForeignKeyConstraint(['cardId'], ['cards.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shareToken')
    )
    op.create_index('ix_shares_active_expiry', 'shares', ['isActive', 'expiryDate'], unique=False)
    op.create_index('ix_shares_cardId', 'shares', ['cardId'], unique=False)
    op.create_index('ix_shares_shareToken', 'shares', ['shareToken'], unique=True)
    op.create_index('ix_shares_userId', 'shares', ['userId'], unique=False)
    op.create_index('ix_shares_user_active', 'shares', ['userId', 'isActive'], unique=False)
    op.create_table('user_card_activities',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='활동 기록 고유 식별자'),
    sa.Column('userId', sa.UUID(), nullable=False, comment='활동 수행 사용자'),
    sa.Column('cardId', sa.UUID(), nullable=False, comment='활동한 카드'),
    sa.Column('activityResult', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='사용자 활동 결과 JSON'),
    sa.Column('completedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='활동 완료 시각'),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='기록 생성 시각'),
    sa.ForeignKeyConstraint(['cardId'], ['cards.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_card_activities_cardId', 'user_card_activities', ['cardId'], unique=False)
    op.create_index('ix_user_card_activities_completedAt', 'user_card_activities', ['completedAt'], unique=False)
    op.create_index('ix_user_card_activities_userId', 'user_card_activities', ['userId'], unique=False)
    op.create_index('ix_user_card_activities_user_card', 'user_card_activities', ['userId', 'cardId'], unique=False)
    op.create_index('ix_user_card_activities_user_completed', 'user_card_activities', ['userId', 'completedAt'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_card_activities_user_completed', table_name='user_card_activities')
    op.drop_index('ix_user_card_activities_user_card', table_name='user_card_activities')
    op.drop_index('ix_user_card_activities_userId', table_name='user_card_activities')
    op.drop_index('ix_user_card_activities_completedAt', table_name='user_card_activities')
    op.drop_index('ix_user_card_activities_cardId', table_name='user_card_activities')
    op.drop_table('user_card_activities')
    op.drop_index('ix_shares_user_active', table_name='shares')
    op.drop_index('ix_shares_userId', table_name='shares')
    op.drop_index('ix_shares_shareToken', table_name='shares')
    op.drop_index('ix_shares_cardId', table_name='shares')
    op.drop_index('ix_shares_active_expiry', table_name='shares')
    op.drop_table('shares')
    op.drop_index('ix_users_userId', table_name='users')
    op.drop_index('ix_users_social_login', table_name='users', postgresql_where=sa.text('"socialProvider" IS NOT NULL'))
    op.drop_table('users')
    op.drop_index('ix_cards_qrCode', table_name='cards')
    op.drop_index('ix_cards_isActive', table_name='cards')
    op.drop_index('ix_cards_activityType', table_name='cards')
    op.drop_table('cards')
    # ### end Alembic commands ###
